const mongoose = require('mongoose');

const productSchema = new mongoose.Schema({
    name: {type: String},
    productId: {type: String},
    randomDataTitle1: {type: String},
    rd1info1: {type: String},
    rd1info1File: {type:String},
    rd1info2: {type: String},
    rd1info2File: {type:String},
    rd1info3: {type: String},
    rd1info3File: {type:String},
    rd1info4: {type: String},
    rd1info4File: {type:String},
    rd1info5: {type: String},
    rd1info5File: {type:String},
    randomDataTitle2: {type: String},
    rd2info1: {type: String},
    rd2info1File: {type:String},
    rd2info2: {type: String},
    rd2info2File: {type:String},
    rd2info3: {type: String},
    rd2info3File: {type:String},
    rd2info4: {type: String},
    rd2info4File: {type:String},
    rd2info5: {type: String},
    rd2info5File: {type:String},
    randomDataTitle3: {type: String},
    rd3info1: {type: String},
    rd3info1File: {type:String},
    rd3info2: {type: String},
    rd3info2File: {type:String},
    rd3info3: {type: String},
    rd3info3File: {type:String},
    rd3info4: {type: String},
    rd3info4File: {type:String},
    rd3info5: {type: String},
    rd3info5File: {type:String},
    randomDataTitle4: {type: String},
    rd4info1: {type: String},
    rd4info1File: {type:String},
    rd4info2: {type: String},
    rd4info2File: {type:String},
    rd4info3: {type: String},
    rd4info3File: {type:String},
    rd4info4: {type: String},
    rd4info4File: {type:String},
    rd4info5: {type: String},
    rd4info5File: {type:String},
    randomDataTitle5: {type: String},
    rd5info1: {type: String},
    rd5info1File: {type:String},
    rd5info2: {type: String},
    rd5info2File: {type:String},
    rd5info3: {type: String},
    rd5info3File: {type:String},
    rd5info4: {type: String},
    rd5info4File: {type:String},
    rd5info5: {type: String},
    rd5info5File: {type:String},
});

const Product = mongoose.model("products",productSchema);

module.exports = Product;
